# Generated by Django 2.1.5 on 2019-02-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_c_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-c_time'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
