# Generated by Django 2.1.5 on 2019-11-01 11:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='评论标题')),
                ('text', models.TextField(max_length=10)),
                ('parent_cmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comdb.Comment')),
            ],
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('be591d4c-00ff-4f4f-98a8-70a4b723d46c'), editable=False),
        ),
    ]
