# Generated by Django 2.0.7 on 2018-08-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
