# Generated by Django 2.1.5 on 2019-11-07 15:58

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comdb', '0002_auto_20191101_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ctime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('83bd801e-8533-4bd8-8485-ebae6e46b42b'), editable=False),
        ),
    ]
