# Generated by Django 2.1.5 on 2019-11-08 10:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comdb', '0004_auto_20191107_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_cmt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comdb.Comment'),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('305cb915-c5f7-4c33-a1fb-3879a5ea7f85'), editable=False),
        ),
    ]
