# Generated by Django 2.1.5 on 2019-11-08 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comdb', '0005_auto_20191108_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ctime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ed3dd182-3701-4ac3-b132-fa1ebe6ad668'), editable=False),
        ),
    ]
