# Generated by Django 2.0.7 on 2019-11-10 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comdb', '0006_auto_20191108_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c4c780f5-d18a-41ad-a215-bd7a5f29ab89'), editable=False),
        ),
    ]
