# Generated by Django 2.1.5 on 2019-02-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comdb', '0006_auto_20190222_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('home_group', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
