# Generated by Django 2.1.5 on 2019-11-19 17:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comdb', '0007_auto_20191110_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutco', to='comdb.question'),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('10117476-b631-4caa-9983-930c0e2ee895'), editable=False),
        ),
    ]
