# Generated by Django 2.1.5 on 2019-02-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comdb', '0007_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student_info',
        ),
    ]
