# Generated by Django 2.1.5 on 2019-02-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comdb', '0008_auto_20190222_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiter',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
    ]
