# Generated by Django 2.1.5 on 2019-02-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comdb', '0009_auto_20190222_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comdb.Place')),
                ('customers', models.ManyToManyField(related_name='provider', to='comdb.Place')),
            ],
            bases=('comdb.place',),
        ),
    ]
